# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['created_time'], 'verbose_name': '应用链接', 'verbose_name_plural': '应用链接'},
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, verbose_name='简要描述'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
    ]
