# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.Post', verbose_name='文章'),
        ),
    ]
