# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 14:35
from __future__ import unicode_literals

import archives.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0009_auto_20161011_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('link', models.URLField(blank=True, null=True, verbose_name='参考链接')),
                ('photo', models.ImageField(upload_to='gift/%Y/%m/%d', validators=[archives.models.check_image_extension], verbose_name='图片')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '礼物',
                'verbose_name_plural': '礼物',
            },
        ),
        migrations.CreateModel(
            name='GiftLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='花费')),
                ('delivery', models.BooleanField(default=False, verbose_name='发货')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='购买者')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Gift', verbose_name='礼物')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '购买记录',
                'verbose_name_plural': '购买记录',
            },
        ),
    ]
