# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_gift_giftlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='show',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
    ]
