# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 15:28
from __future__ import unicode_literals

import archives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0011_gift_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['-amount', '-created_time'], 'verbose_name': '礼物', 'verbose_name_plural': '礼物'},
        ),
        migrations.AddField(
            model_name='gift',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gift/%Y/%m/%d', validators=[archives.models.check_image_extension], verbose_name='图片'),
        ),
    ]
