# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0012_auto_20161012_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftlog',
            name='address',
            field=models.CharField(help_text='填写收件地址，虚拟物品则填写邮箱或QQ', max_length=512, null=True, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='giftlog',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
