# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0013_auto_20161013_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftlog',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货时间'),
        ),
        migrations.AlterField(
            model_name='giftlog',
            name='remark',
            field=models.TextField(blank=True, help_text='没有则无需填写', null=True, verbose_name='备注'),
        ),
    ]
