# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0014_auto_20161013_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'ordering': ['-price'], 'verbose_name': '礼物', 'verbose_name_plural': '礼物'},
        ),
        migrations.AddField(
            model_name='giftlog',
            name='reply',
            field=models.TextField(blank=True, help_text='发货订单号等', null=True, verbose_name='管理员回复'),
        ),
    ]
