# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0016_auto_20161014_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='评价'),
        ),
    ]
