# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0017_post_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
