# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 12:51
from __future__ import unicode_literals

import archives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0018_remove_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, upload_to=archives.models.generate_attachment_filename, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='file',
            field=models.ImageField(blank=True, upload_to=archives.models.generate_image_filename, verbose_name='图片'),
        ),
    ]
