# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161005_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.CharField(choices=[('anonymous', '路人甲'), ('practice', '见习白帽'), ('general', '正式白帽'), ('senior', '高级白帽'), ('supreme', '核心白帽'), ('god', '妇科圣手')], default='anonymous', max_length=16, verbose_name='等级'),
        ),
    ]
