# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.CharField(blank=True, max_length=512, verbose_name='个人简介'),
        ),
    ]
