# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_member_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.CharField(choices=[('anonymous', '路人甲'), ('practice', '见习白帽子'), ('general', '正式白帽子'), ('senior', '高级白帽子'), ('supreme', '核心白帽子'), ('god', '妇科圣手')], default='anonymous', max_length=16, verbose_name='等级'),
        ),
    ]
