# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20161010_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='used_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用时间'),
        ),
    ]
