# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 17:55
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20161010_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='邀请码'),
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mugshot',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.generate_upload_filename, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='用户名'),
        ),
    ]
