# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20161011_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-rank', '-date_joined']},
        ),
    ]
