# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20161011_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_auditor',
            field=models.BooleanField(default=False, help_text='是否能够进入审核后台', verbose_name='审核员'),
        ),
    ]
