# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 12:50
from __future__ import unicode_literals

import accounts.models
import archives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_member_is_auditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mugshot',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.generate_upload_filename, validators=[archives.models.check_image_extension], verbose_name='头像'),
        ),
    ]
