# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinlog',
            options={'ordering': ['-created_time']},
        ),
    ]
