# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_auto_20161010_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinlog',
            name='message',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='原因'),
        ),
    ]
