#!/usr/bin/env bash

set -eo pipefail

until psql -h "${DB_HOST}" -U "postgres" -c '\l'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up - executing command"

python manage.py collectstatic --noinput && python manage.py migrate && python manage.py initadmin